# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 45

# Issues with these labels will never be considered stale
exemptLabels:
  - bug
  - enhancement

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: true

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: true

# Set to true to ignore issues with an assignee (defaults to false)
exemptAssignees: true

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This pull request has been automatically marked as stale because it has not had
  activity in the last 30 day. It will be closed in 15 days if no further activity occurs. 
  Please feel free to give a status update now, ping for review, or re-open when it's ready.

  Thank you for your contributions!

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This pull request has been automatically closed because it has not had
  activity in the last 45 days. Please feel free to give a status update now, 
  ping for review, or re-open when it's ready.
  
  Thank you for your contributions!

# Limit to only `issues` or `pulls`
only: issues