name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Hello and welcome! Thanks for creating your first issue! Someone from our community will get back to you soon!'
          pr-message: >
            Thanks for opening your first pull reqest in VSCode G-Code Syntax!
            
            Please make sure you read the [Contributing Guide](https://github.com/appliedengdesign/vscode-gcode-syntax/blob/master/CONTRIBUTING.md) and follow the [Code of Conduct](https://github.com/appliedengdesign/vscode-gcode-syntax/blob/master/CODE_OF_CONDUCT.md).